export interface JahiaComponent {
  /** The ID of the component (autogenerated but can be overridden) */
  id?: string;
  /**
   * The name of the component.
   *
   * @default "default"
   */
  name?: string;
  /** The display name of the component (in jahia's UI), optional. */
  displayName?: string;
  /** The type of the component. */
  componentType: "template" | "view";
  /** The content node type the component applies to. */
  nodeType: string;
  /** Properties to add on the component, optional. */
  properties?: Record<string, string>;
}

/**
 * Using this function provides autocomplete on the jahiaComponent properties.
 *
 * @param jahiaComponent - An object containing the Jahia component to define.
 * @returns The jahiaComponent object.
 */
export function defineJahiaComponent(jahiaComponent: JahiaComponent): JahiaComponent {
  return jahiaComponent;
}
