version: 2
updates:
  # Ensure the latest @jahia/cypress package is used
  - package-ecosystem: "npm" # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#yarn
    directory: "javascript-modules-engine/tests/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@jahia/cypress"
        dependency-type: "development"
