name: Build
on: [push]
jobs:
  build-and-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: corepack enable
      - name: Install dependencies
        run: yarn install
      - name: Bundle package
        run: yarn build
      - name: Upload package.tgz
        uses: actions/upload-artifact@v4
        with:
          name: package.tgz
          path: dist/package.tgz
