import { parse, stringify } from "devalue";

/**
 * Registers every function exported by a `.action.ts` file as a callable action.
 *
 * Do not call this function yourself: `@jahia/vite-plugin` appends a call to it to every
 * `.action.ts` file in the server bundle (declare actions by exporting functions from such a file).
 * It stays in the main entry point only because the engine resolves the library as a single shared
 * module at runtime; the underscore marks it as internal.
 *
 * The registered adapter is invoked by the engine's generic action endpoint
 * (`GenericActionEndpoint`) with the raw devalue-serialized arguments array, and resolves to the
 * devalue-serialized result — keep both shapes in sync.
 *
 * Action keys are `<moduleName>/<exportName>`; the client stubs generated by the vite plugin use
 * the same convention. Registering twice with the same key (duplicate export names across the
 * `.action.ts` files of a module) fails at module startup.
 *
 * @internal
 */
export const __registerActionsModule = (
  actions: Record<string, unknown>,
  moduleName: string,
): void => {
  for (const [name, fn] of Object.entries(actions)) {
    if (typeof fn !== "function") continue;
    server.registry.add("action", `${moduleName}/${name}`, {
      execute: (body: string) =>
        Promise.resolve()
          .then(() => fn(...(parse(body) as unknown[])))
          .then(
            (result) => stringify(result),
            (error: unknown) => {
              // Shape the rejection for the Java endpoint: a plain object with a string message
              // and, for validation failures, pre-stringified issues.
              const shaped: { message: string; issues?: string } = { message: messageOf(error) };
              const issues = (error as { issues?: unknown } | undefined)?.issues;
              if (Array.isArray(issues)) {
                shaped.issues = JSON.stringify(issues);
              }
              throw shaped;
            },
          ),
    });
    console.debug(`Registered action: ${moduleName}/${name}`);
  }
};

/** Extracts a human-readable message from an Error, an error-like object, or anything else. */
const messageOf = (error: unknown): string => {
  if (error instanceof Error) return error.message;
  const message = (error as { message?: unknown } | undefined)?.message;
  return String(message ?? error);
};
