import { parse, stringify } from "devalue";
import { ActionError, ActionValidationError } from "./action.js";

/**
 * Registers every function exported by a `.action.ts` file as a callable action.
 *
 * Do not call this function yourself: `@jahia/vite-plugin` appends a call to it to every
 * `.action.ts` file in the server bundle (declare actions by exporting functions from such a file).
 * It stays in the main entry point only because the engine resolves the library as a single shared
 * module at runtime; the underscore marks it as internal.
 *
 * The registered adapter is invoked by the engine's generic action endpoint
 * (`GenericActionEndpoint`) with the raw devalue-serialized arguments array, and resolves to the
 * devalue-serialized result — keep both shapes in sync.
 *
 * Action keys are `<moduleName>/<exportName>`; the client stubs generated by the vite plugin use
 * the same convention. Registering twice with the same key (duplicate export names across the
 * `.action.ts` files of a module) fails at module startup.
 *
 * @internal
 */
export const __registerActionsModule = (
  actions: Record<string, unknown>,
  moduleName: string,
): void => {
  for (const [name, fn] of Object.entries(actions)) {
    if (typeof fn !== "function") {
      console.warn(
        `Skipping non-function export "${name}" of an action file in ${moduleName}: only functions can be actions (its generated client stub will fail if called)`,
      );
      continue;
    }
    server.registry.add("action", `${moduleName}/${name}`, {
      execute: (body: string) =>
        Promise.resolve()
          .then(() => fn(...(parse(body) as unknown[])))
          .then(
            (result) => stringify(result),
            (error: unknown) => {
              // Shape the rejection for the Java endpoint: a plain object with a string message
              // and, for validation failures, pre-stringified issues. Actions are guest-callable:
              // only deliberate error types carry their message to the caller, anything else is
              // logged here and replaced by a generic message (unexpected messages can leak
              // implementation details, node paths or permissions).
              const issues = (error as { issues?: unknown } | undefined)?.issues;
              const deliberate =
                Array.isArray(issues) ||
                error instanceof ActionError ||
                error instanceof ActionValidationError;
              const shaped: { message: string; issues?: string } = {
                message: deliberate ? messageOf(error) : "Action execution failed",
              };
              if (Array.isArray(issues)) {
                shaped.issues = JSON.stringify(issues);
              }
              if (!deliberate) {
                console.error(`Action ${moduleName}/${name} threw: ${messageOf(error)}`);
              }
              throw shaped;
            },
          ),
    });
    console.debug(`Registered action: ${moduleName}/${name}`);
  }
};

/** Extracts a human-readable message from an Error, an error-like object, or anything else. */
const messageOf = (error: unknown): string => {
  if (error instanceof Error) return error.message;
  const message = (error as { message?: unknown } | undefined)?.message;
  return String(message ?? error);
};
