name: On Merge

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - '**'

permissions:
  actions: read
  checks: write
  contents: read

concurrency:
  # ensure there is at most one execution of this workflow at any time
  # if another workflow is "in progress", the queued workflow will be "pending"
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  merge:
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-module-on-merge.yml@reusable-module-workflows
    secrets: inherit
