# This workflow ensures that Windows builds are exactly the same as on other platforms

name: Test on Windows

on:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: latest
          check-latest: true

      - name: Install and build dependencies
        run: |
          corepack enable
          yarn install
          yarn workspace "@jahia/vite-plugin" build

      - name: Run tests
        run: |
          set FORCE_COLOR=1
          yarn workspace "@jahia/vite-plugin" test
