# This workflow ensures that Windows builds are exactly the same as on other platforms

name: Test on Windows

on:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - # https://github.com/actions/checkout/issues/135#issuecomment-602171132
        name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: latest
          check-latest: true

      - name: Install and build dependencies
        run: |
          corepack enable
          yarn install
          yarn workspace "@jahia/vite-plugin" build

      - name: Run tests
        run: yarn workspace "@jahia/vite-plugin" test
